### ISSUE TITLE
Import Error for sh scrips/coach_rnn500.sh

### ISSUE THREAD

**Issue by Shengyu-Feng** [facebookresearch/minirts#1]
Hi, I have the following error when I tried to run `sh scripts/coach_rnn500.sh`, I can't tell exactly where that google module is from, any help is appreciated. 
`
Traceback (most recent call last):
  File "train_coach.py", line 18, in <module>
    from coach_dataset import CoachDataset, compute_cache
  File "/home/km/myagent/minirts/scripts/behavior_clone/coach_dataset.py", line 13, in <module>
    from dataset import BehaviorCloneDataset
  File "/home/km/myagent/minirts/scripts/behavior_clone/dataset.py", line 14, in <module>
    from common_utils import assert_eq, assert_neq
  File "/home/km/myagent/minirts/scripts/behavior_clone/common_utils/__init__.py", line 11, in <module>
    from .multi_counter import MultiCounter
  File "/home/km/myagent/minirts/scripts/behavior_clone/common_utils/multi_counter.py", line 10, in <module>
    from tensorboardX import SummaryWriter
  File "/home/km/anaconda3/envs/minirts/lib/python3.5/site-packages/tensorboardX/__init__.py", line 5, in <module>
    from .torchvis import TorchVis
  File "/home/km/anaconda3/envs/minirts/lib/python3.5/site-packages/tensorboardX/torchvis.py", line 11, in <module>
    from .writer import SummaryWriter
  File "/home/km/anaconda3/envs/minirts/lib/python3.5/site-packages/tensorboardX/writer.py", line 15, in <module>
    from .event_file_writer import EventFileWriter
  File "/home/km/anaconda3/envs/minirts/lib/python3.5/site-packages/tensorboardX/event_file_writer.py", line 28, in <module>
    from .proto import event_pb2
  File "/home/km/anaconda3/envs/minirts/lib/python3.5/site-packages/tensorboardX/proto/event_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/home/km/anaconda3/envs/minirts/lib/python3.5/site-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: /home/km/anaconda3/envs/minirts/lib/python3.5/site-packages/google/protobuf/pyext/_message.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZNK6google8protobuf10TextFormat17FieldValuePrinter9PrintBoolEb`

**Comment by hengyuan-hu** [comment]
It looks like that it is from `tensorboardX`. You may try disabling `tensorboard` by commenting out related code.
